### ISSUE TITLE
Can I see your papers, please

### ISSUE THREAD

**Issue by inspirelove** [JulioGV/ContentDrivenAutomaticEqualizationForAudio#1]
Can I see your papers, please

**Comment by JulioGV** [comment]
What do you mean?

**Comment by inspirelove** [comment]
Recently I was learning about audio equalizer. I accidentally discovered your project. I'm very happy to find that your project matches the function I want to achieve. So I wanted to refer to your paper, but found that I couldn't find it online.

**Comment by inspirelove** [comment]
I don't know if your paper has been published. If not, I'm sorry to bother you.

**Comment by JulioGV** [comment]
I'm still working on the paper (it's my bachelor's thesis), it should be finished in about 2-3 weeks, I can send it to you then if you give me your email.

**Comment by inspirelove** [comment]
Okay, thank you very much, my email is 439601575@qq.com
